### ISSUE TITLE
NOTE_DIR gets overwritten

### ISSUE THREAD

**Issue by Madic-** [dcchambers/note-keeper#49]
NOTE_DIR shouldn't be overwritten with extra paths in line 20. It adds directories that maybe aren't wanted.

Just set full default NOTE_DIR in line 11 and let the user decide in which directory the notes should be stored

**Comment by dcchambers** [comment]
So the reason I add `year/month/day` directories is for organization - rather than just dumping all notes into a single directory, they are organized in a way that is logical (to me, anyway).

I probably should rename that variable to `NOTE_PATH` to more accurately reflect what is happening.

This is probably something that could be configured in the config file, but I don't think I will change the default behavior.

**Comment by dcchambers** [comment]
I just [released Notekeeper 1.1](https://github.com/dcchambers/note-keeper/releases/tag/v1.1) which implements an `organize_by_date` variable that you can set in your `noterc` configuration file.

The default is `true` - so set `organize_by_date=false` in your `noterc` file and it will skip the `.../$YEAR/$MONTH/$DAY/...` directory organization.

Hope this helps!
